window.AUS155 = {
  "version": "AUS155-2026-06-30.3",
  "settings": {
    "companyName": "AxiCorp Pte Ltd (Singapore) — AUS155",
    "currency": "$",
    "fyEndMonth": 6,
    "fyEndDay": 30,
    "reportingDate": "2026-06-30"
  },
  "assets": [
    {
      "id": "AUS155-0001",
      "tag": "A2200008",
      "category": "140100-Computer Equipment",
      "description": "Lenovo TP X1 Yoga G5 i7 (2)",
      "location": "",
      "department": "IT - Support",
      "custodian": "",
      "acquisitionDate": "2021-08-20",
      "supplier": "CNAN004",
      "invoice": "INV/2021/5653",
      "purchaseCost": "5125.56",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 6955 SGD. Internal ID 875098. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0002",
      "tag": "A2200016",
      "category": "140100-Computer Equipment",
      "description": "20XYCTO1WW Lenovo ThinkPad X1 Yoga Gen 6 (Qty 18)",
      "location": "",
      "department": "IT - Support",
      "custodian": "",
      "acquisitionDate": "2021-09-16",
      "supplier": "CKGS001",
      "invoice": "INV/2021/0467",
      "purchaseCost": "45854.02",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 62220.5 SGD. Internal ID 875099. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0003",
      "tag": "A2200017",
      "category": "140100-Computer Equipment",
      "description": "Lenovo ThinkPad X1 Yoga Gen 6",
      "location": "",
      "department": "IT - Support",
      "custodian": "",
      "acquisitionDate": "2021-09-23",
      "supplier": "CKGS001",
      "invoice": "INV/2021/0474-2",
      "purchaseCost": "12912.46",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 17521.25 SGD. Internal ID 875100. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0004",
      "tag": "A2200020",
      "category": "140100-Computer Equipment",
      "description": "1 x Lenovo YOGA 7 and 1x ThinkPad Universal USB-C Dock - UK",
      "location": "",
      "department": "IT - Support",
      "custodian": "",
      "acquisitionDate": "2021-10-07",
      "supplier": "CKGS001",
      "invoice": "INV/2021/0545",
      "purchaseCost": "1931.94",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 2621.5 SGD. Internal ID 875101. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0005",
      "tag": "A2200021",
      "category": "140100-Computer Equipment",
      "description": "LENOVO THINKVISION T24I-2L 23.8\" MONITOR (VGA + HDMI + DP) - FHD",
      "location": "",
      "department": "IT - Support",
      "custodian": "",
      "acquisitionDate": "2021-10-01",
      "supplier": "CINN001",
      "invoice": "191036",
      "purchaseCost": "1931.94",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 2621.5 SGD. Internal ID 875102. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0006",
      "tag": "A2200022",
      "category": "140100-Computer Equipment",
      "description": "7 x ThinkPad Yoga G6 & 7 x USB C Dock & 7 x ThinkVision Monitor & 7 x Lenovo Wireless Keyboard",
      "location": "",
      "department": "IT - Support",
      "custodian": "",
      "acquisitionDate": "2021-10-12",
      "supplier": "CNAN004",
      "invoice": "79912",
      "purchaseCost": "18988.22",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 25765.6 SGD. Internal ID 875103. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0007",
      "tag": "A2200034",
      "category": "140100-Computer Equipment",
      "description": "10x ThinkPad, 20x Monitor , 10x KB & Mouse",
      "location": "",
      "department": "IT - Support",
      "custodian": "",
      "acquisitionDate": "2021-11-12",
      "supplier": "CNAN004",
      "invoice": "INV/2021/7457",
      "purchaseCost": "5835.25",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 7918 SGD. Internal ID 875104. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0008",
      "tag": "A2200035",
      "category": "140100-Computer Equipment",
      "description": "ThinkPad Yoga G6, - 10 items",
      "location": "",
      "department": "IT - Support",
      "custodian": "",
      "acquisitionDate": "2021-11-12",
      "supplier": "CNAN004",
      "invoice": "INV/2021/7458",
      "purchaseCost": "23222.72",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 31511.5 SGD. Internal ID 875105. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0009",
      "tag": "A2200036",
      "category": "140100-Computer Equipment",
      "description": "11 x Lenovo ThinkPad X1 Yoga Gen 6",
      "location": "",
      "department": "IT - Support",
      "custodian": "",
      "acquisitionDate": "2021-11-23",
      "supplier": "CKGS001",
      "invoice": "INV/2021/0687",
      "purchaseCost": "26611.89",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 36110.36 SGD. Internal ID 875106. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0010",
      "tag": "A2200039",
      "category": "140100-Computer Equipment",
      "description": "Jabra Evolve 40 UC Stereo Office Headset, USB-A, 3.5mm",
      "location": "",
      "department": "IT - Support",
      "custodian": "",
      "acquisitionDate": "2021-10-12",
      "supplier": "CHEA003",
      "invoice": "DBS Order ID #20070",
      "purchaseCost": "943.25",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 1279.92 SGD. Internal ID 875107. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0011",
      "tag": "A2200045",
      "category": "140100-Computer Equipment",
      "description": "10 Jabra Evolve 40 UC Stereo Office Headset",
      "location": "",
      "department": "IT - Development",
      "custodian": "",
      "acquisitionDate": "2021-12-03",
      "supplier": "CHEA003",
      "invoice": "202112 DBS",
      "purchaseCost": "1179.06",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 1599.9 SGD. Internal ID 875108. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0012",
      "tag": "A2200077",
      "category": "140100-Computer Equipment",
      "description": "ThinkBook 14 Gen2 ITL (1)",
      "location": "",
      "department": "Technology Operations",
      "custodian": "",
      "acquisitionDate": "2022-05-24",
      "supplier": "CKGS001",
      "invoice": "INV/2022/00447",
      "purchaseCost": "1186.15",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 1626.4 SGD. Internal ID 1058261. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0013",
      "tag": "A2200078",
      "category": "140100-Computer Equipment",
      "description": "Lenovo ThinkPad X1 Yoga Gen5 IML (12), USB docks (12), monitors (24), mouse (12)",
      "location": "",
      "department": "Technology Operations",
      "custodian": "",
      "acquisitionDate": "2022-05-13",
      "supplier": "CKGS001",
      "invoice": "INV/2022/00425",
      "purchaseCost": "39706.01",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 55314.72 SGD. Internal ID 1058262. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0014",
      "tag": "A2300010",
      "category": "140100-Computer Equipment",
      "description": "1 Prism X490 Monitor",
      "location": "",
      "department": "Technology Operations",
      "custodian": "",
      "acquisitionDate": "2022-07-26",
      "supplier": "CKGS001",
      "invoice": "INV/2022/00641",
      "purchaseCost": "2140.43",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 2974.6 SGD. Internal ID 1230047. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0015",
      "tag": "A2300011",
      "category": "140100-Computer Equipment",
      "description": "1 ThinkPad X1 Yoga Gen7",
      "location": "",
      "department": "Technology Operations",
      "custodian": "",
      "acquisitionDate": "2022-07-28",
      "supplier": "CKGS001",
      "invoice": "INV/2022/00650",
      "purchaseCost": "3257.88",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 4494 SGD. Internal ID 1230048. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0016",
      "tag": "A2300026",
      "category": "140100-Computer Equipment",
      "description": "Botanica & Co",
      "location": "",
      "department": "APAC Sales",
      "custodian": "",
      "acquisitionDate": "2022-09-01",
      "supplier": "ESG0070",
      "invoice": "1D678BB2696C4C4F8973",
      "purchaseCost": "1037.71",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Internal ID 1276885. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0017",
      "tag": "A2300029",
      "category": "140100-Computer Equipment",
      "description": "ThinkPad Universal USB-C Dock (10); ThinkPad X1 Yoga G7(4); Lenovo ESSENTIAL WIRELESS KEYBOARD AND MOUSE (10)",
      "location": "",
      "department": "Technology Operations",
      "custodian": "",
      "acquisitionDate": "2022-11-30",
      "supplier": "CKGS001",
      "invoice": "INV/2022/00956",
      "purchaseCost": "15993.59",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Internal ID 1405649. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0018",
      "tag": "A2300031",
      "category": "140100-Computer Equipment",
      "description": "HEADPHONES SG (Jabra Headsets 1qty)",
      "location": "",
      "department": "Technology Operations",
      "custodian": "",
      "acquisitionDate": "2022-11-09",
      "supplier": "CHEA003",
      "invoice": "202211 DBS",
      "purchaseCost": "887.51",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Internal ID 1405650. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0019",
      "tag": "A2300032",
      "category": "140100-Computer Equipment",
      "description": "HEADPHONES SG (Jabra Evolve 40 UC Stereo Office Headset, USB-A, 3.5mm - 15qty)",
      "location": "",
      "department": "Technology Operations",
      "custodian": "",
      "acquisitionDate": "2022-11-24",
      "supplier": "CHEA003",
      "invoice": "202211 DBS",
      "purchaseCost": "2017.57",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Internal ID 1405651. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0020",
      "tag": "A2300039",
      "category": "140100-Computer Equipment",
      "description": "CDCO001\\DC-IV-202303-802\\Laptop",
      "location": "",
      "department": "Technology Operations",
      "custodian": "",
      "acquisitionDate": "2023-03-22",
      "supplier": "CDCO001",
      "invoice": "DC-IV-202303-802",
      "purchaseCost": "1867.1",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Internal ID 1863093. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0021",
      "tag": "A2300040",
      "category": "140100-Computer Equipment",
      "description": "CDCO001\\DC-IV-202303-802\\Laptop",
      "location": "155 - AXICORP PTE. LTD (SG) USD",
      "department": "Technology Operations",
      "custodian": "",
      "acquisitionDate": "2023-03-22",
      "supplier": "CDCO001",
      "invoice": "DC-IV-202303-802",
      "purchaseCost": "1867.1",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Internal ID 2121831. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0022",
      "tag": "APY00045",
      "category": "140100-Computer Equipment",
      "description": "Juniper Switches for SG",
      "location": "SINGAPORE",
      "department": "IT - Support",
      "custodian": "",
      "acquisitionDate": "2019-08-20",
      "supplier": "CMIS001",
      "invoice": "1098281",
      "purchaseCost": "13023.76",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 18624 AUD. Internal ID 876221. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0023",
      "tag": "APY00046",
      "category": "140100-Computer Equipment",
      "description": "3x LG LED TV w/ Swivel bracket & installation",
      "location": "SINGAPORE",
      "department": "Corporate",
      "custodian": "",
      "acquisitionDate": "2019-08-21",
      "supplier": "CMEG003",
      "invoice": "BRI-RG6-38112",
      "purchaseCost": "3441.67",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 4670.09 SGD. Internal ID 876222. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0024",
      "tag": "APY00047",
      "category": "140100-Computer Equipment",
      "description": "2x Lenovo Thinkpad Thunderbolt 3 dock",
      "location": "SINGAPORE",
      "department": "IT - Support",
      "custodian": "",
      "acquisitionDate": "2019-08-28",
      "supplier": "CINN001",
      "invoice": "131678",
      "purchaseCost": "471.65",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 640 SGD. Internal ID 876223. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0025",
      "tag": "APY00069",
      "category": "140100-Computer Equipment",
      "description": "IS_001 - Cyber FX Trade Server equipment",
      "location": "INDONESIA",
      "department": "Institutional - Sales",
      "custodian": "",
      "acquisitionDate": "2019-10-31",
      "supplier": "CCYB001",
      "invoice": "735",
      "purchaseCost": "12564.12",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 17966.71 AUD. Internal ID 876224. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0026",
      "tag": "APY00076",
      "category": "140100-Computer Equipment",
      "description": "6x Lenovo Thinkvision 23.8\" monitor",
      "location": "SINGAPORE",
      "department": "IT - Support",
      "custodian": "",
      "acquisitionDate": "2019-11-04",
      "supplier": "CINN001",
      "invoice": "136290",
      "purchaseCost": "1414.96",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 1920 SGD. Internal ID 876225. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0027",
      "tag": "APY00077",
      "category": "140100-Computer Equipment",
      "description": "2x Lenovo thinkvision 23.8\" monitor",
      "location": "",
      "department": "IT - Support",
      "custodian": "",
      "acquisitionDate": "2020-02-05",
      "supplier": "CINN001",
      "invoice": "141940",
      "purchaseCost": "471.65",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 640 SGD. Internal ID 876226. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0028",
      "tag": "APY00078",
      "category": "140100-Computer Equipment",
      "description": "2x Lenovo thinkpad thunderbolt 3 dock Gen",
      "location": "",
      "department": "IT - Support",
      "custodian": "",
      "acquisitionDate": "2020-02-05",
      "supplier": "CINN001",
      "invoice": "141940",
      "purchaseCost": "515.87",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 700 SGD. Internal ID 876227. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0029",
      "tag": "APY00079",
      "category": "140100-Computer Equipment",
      "description": "1x Lenovo USB-C to USB-C cable",
      "location": "",
      "department": "IT - Support",
      "custodian": "",
      "acquisitionDate": "2020-02-05",
      "supplier": "CINN001",
      "invoice": "141940",
      "purchaseCost": "36.85",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 50 SGD. Internal ID 876228. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0030",
      "tag": "APY00080",
      "category": "140100-Computer Equipment",
      "description": "2x Logitech MK120 USB desktop combo",
      "location": "",
      "department": "IT - Support",
      "custodian": "",
      "acquisitionDate": "2020-02-05",
      "supplier": "CINN001",
      "invoice": "141940",
      "purchaseCost": "29.48",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 40 SGD. Internal ID 876229. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0031",
      "tag": "APY00094",
      "category": "140100-Computer Equipment",
      "description": "H Kher - Lenovo thinkvsion Monitor",
      "location": "",
      "department": "IT - Support",
      "custodian": "",
      "acquisitionDate": "2020-06-01",
      "supplier": "EUK0059",
      "invoice": "EXP51281",
      "purchaseCost": "286.37",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 388.58 SGD. Internal ID 876230. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0032",
      "tag": "APY00095",
      "category": "140100-Computer Equipment",
      "description": "H Kher - Lenovo keyboard & mouse",
      "location": "",
      "department": "IT - Support",
      "custodian": "",
      "acquisitionDate": "2020-06-01",
      "supplier": "EUK0059",
      "invoice": "EXP51281",
      "purchaseCost": "78.62",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 106.68 SGD. Internal ID 876231. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0033",
      "tag": "APY00096",
      "category": "140100-Computer Equipment",
      "description": "H Kher - Dericam webcam ultra HD",
      "location": "",
      "department": "IT - Support",
      "custodian": "",
      "acquisitionDate": "2020-06-01",
      "supplier": "EUK0059",
      "invoice": "EXP51281",
      "purchaseCost": "65.07",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 88.3 SGD. Internal ID 876232. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0034",
      "tag": "APY00110",
      "category": "140100-Computer Equipment",
      "description": "H Kher - laptopdirect 10/07/20",
      "location": "",
      "department": "Corporate",
      "custodian": "",
      "acquisitionDate": "2020-07-13",
      "supplier": "EUK0059",
      "invoice": "EXP51296",
      "purchaseCost": "227.89",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 309.23 SGD. Internal ID 876233. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0035",
      "tag": "APY00112",
      "category": "140100-Computer Equipment",
      "description": "S Tay - 1x Logitech Full HD Pro Webcam 17/04/20",
      "location": "",
      "department": "Retail - Operations",
      "custodian": "",
      "acquisitionDate": "2020-07-01",
      "supplier": "ESG0030",
      "invoice": "EXP51299",
      "purchaseCost": "147.75",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 200.49 SGD. Internal ID 876234. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0036",
      "tag": "APY00113",
      "category": "140100-Computer Equipment",
      "description": "H Kher - 1x Jabra Speak 510 USB phone 20/07/20",
      "location": "",
      "department": "Corporate",
      "custodian": "",
      "acquisitionDate": "2020-07-21",
      "supplier": "EUK0059",
      "invoice": "EXP51301",
      "purchaseCost": "108.17",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 146.78 SGD. Internal ID 876235. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0037",
      "tag": "APY00119",
      "category": "140100-Computer Equipment",
      "description": "10x Lenovo Thinkvision T24I-20 23.8\" monitor",
      "location": "",
      "department": "IT - Support",
      "custodian": "",
      "acquisitionDate": "2020-10-22",
      "supplier": "CINN001",
      "invoice": "160177",
      "purchaseCost": "1731.86",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 2350 SGD. Internal ID 876236. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0038",
      "tag": "APY00130",
      "category": "140100-Computer Equipment",
      "description": "10x Lenovo Thinkvision T24I-20",
      "location": "SINGAPORE",
      "department": "IT - Support",
      "custodian": "",
      "acquisitionDate": "2020-12-21",
      "supplier": "CINN001",
      "invoice": "165416",
      "purchaseCost": "121.23",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 164.5 SGD. Internal ID 876237. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0039",
      "tag": "APY00139",
      "category": "140100-Computer Equipment",
      "description": "4x Lenovo Thinkpad Hybrid USB-C w/ dock",
      "location": "SINGAPORE",
      "department": "IT - Support",
      "custodian": "",
      "acquisitionDate": "2021-01-26",
      "supplier": "CINN001",
      "invoice": "168330",
      "purchaseCost": "1084.81",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 1472 SGD. Internal ID 876238. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0040",
      "tag": "APY00144",
      "category": "140100-Computer Equipment",
      "description": "ThinkPad X1 Yoga Gen5, Intel Core i7",
      "location": "",
      "department": "IT - Support",
      "custodian": "",
      "acquisitionDate": "2021-04-21",
      "supplier": "CNAN004",
      "invoice": "IN2021-43976",
      "purchaseCost": "2395.12",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 3250 SGD. Internal ID 876239. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0041",
      "tag": "AUS155-0001",
      "category": "140100-Computer Equipment",
      "description": "Lenovo ThinkCentre M70s Gen 4",
      "location": "",
      "department": "Corporate - Executive",
      "custodian": "",
      "acquisitionDate": "2024-02-01",
      "supplier": "",
      "invoice": "",
      "purchaseCost": "1451.6",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Internal ID 3491437. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0042",
      "tag": "AUS155-0002",
      "category": "140100-Computer Equipment",
      "description": "ThinkStation P14s Gen4",
      "location": "",
      "department": "Corporate - Executive",
      "custodian": "",
      "acquisitionDate": "2024-06-13",
      "supplier": "CKGS001",
      "invoice": "INV/2024/00310",
      "purchaseCost": "1815.24",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Internal ID 4181880. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0043",
      "tag": "AUS155-0003",
      "category": "140100-Computer Equipment",
      "description": "ThinkStation P14s Gen4",
      "location": "",
      "department": "Corporate - Executive",
      "custodian": "",
      "acquisitionDate": "2024-06-13",
      "supplier": "CKGS001",
      "invoice": "INV/2024/00310",
      "purchaseCost": "1815.24",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Internal ID 4181881. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0044",
      "tag": "AUS155-0004",
      "category": "140100-Computer Equipment",
      "description": "ThinkStation P14s Gen4",
      "location": "",
      "department": "Corporate - Executive",
      "custodian": "",
      "acquisitionDate": "2024-06-13",
      "supplier": "CKGS001",
      "invoice": "INV/2024/00310",
      "purchaseCost": "1815.24",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Internal ID 4181882. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0045",
      "tag": "AUS155-0005",
      "category": "140100-Computer Equipment",
      "description": "ThinkStation P14s Gen4",
      "location": "",
      "department": "Corporate - Executive",
      "custodian": "",
      "acquisitionDate": "2024-06-13",
      "supplier": "CKGS001",
      "invoice": "INV/2024/00310",
      "purchaseCost": "1815.24",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Internal ID 4181883. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0046",
      "tag": "AUS155-0006",
      "category": "140100-Computer Equipment",
      "description": "ThinkStation P14s Gen4",
      "location": "",
      "department": "Corporate - Executive",
      "custodian": "",
      "acquisitionDate": "2024-06-13",
      "supplier": "CKGS001",
      "invoice": "INV/2024/00310",
      "purchaseCost": "1815.24",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Internal ID 4181884. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0047",
      "tag": "AUS155-0019",
      "category": "140100-Computer Equipment",
      "description": "4x ThinkStation P14s Gen 5 and Premier Support",
      "location": "Singapore-AUS155",
      "department": "Technology Operations",
      "custodian": "",
      "acquisitionDate": "2024-08-30",
      "supplier": "KG Sowers Group Pte Ltd",
      "invoice": "INV/2024/00453",
      "purchaseCost": "9510.49",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Internal ID 4739205. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0048",
      "tag": "AUS155-0020",
      "category": "140100-Computer Equipment",
      "description": "ThinkStation P14s Gen 5",
      "location": "Singapore-AUS155",
      "department": "Technology Operations",
      "custodian": "",
      "acquisitionDate": "2024-10-14",
      "supplier": "KG Sowers Group Pte Ltd",
      "invoice": "INV/2024/00546",
      "purchaseCost": "11246.23",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Internal ID 4739212. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0049",
      "tag": "AUS155-0021",
      "category": "140100-Computer Equipment",
      "description": "SG Boardroom and Video Setup",
      "location": "Singapore-AUS155",
      "department": "Technology Operations",
      "custodian": "",
      "acquisitionDate": "2024-10-17",
      "supplier": "ByteBridge Technology PTE LTD",
      "invoice": "SO-6500079",
      "purchaseCost": "12005.21",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Internal ID 4739213. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0050",
      "tag": "AUS155-0022",
      "category": "140100-Computer Equipment",
      "description": "Samsung 65\" Crystal UHD Signage QB65C and Office set up",
      "location": "Singapore-AUS155",
      "department": "Technology Operations",
      "custodian": "",
      "acquisitionDate": "2024-11-06",
      "supplier": "KG Sowers Group Pte Ltd",
      "invoice": "INV/2024/00582",
      "purchaseCost": "2539.05",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Internal ID 4739259. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0051",
      "tag": "AUS155-0023",
      "category": "140100-Computer Equipment",
      "description": "MacBook Pro 16in, Apple M4 Max,48GB,1TB Storage",
      "location": "Singapore-AUS155",
      "department": "Technology Operations",
      "custodian": "",
      "acquisitionDate": "2024-12-23",
      "supplier": "KG Sowers (Malaysia) Sdn Bhd",
      "invoice": "KGM/2024/0002",
      "purchaseCost": "40270",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Internal ID 4739302. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0052",
      "tag": "AUS155-0031",
      "category": "140100-Computer Equipment",
      "description": "16-inch MacBook Pro - Space Black",
      "location": "Singapore-AUS155",
      "department": "Technology Operations",
      "custodian": "",
      "acquisitionDate": "2025-01-22",
      "supplier": "KG Sowers Group Pte Ltd",
      "invoice": "INV/2025/00051",
      "purchaseCost": "3790.05",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Internal ID 5542772. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0053",
      "tag": "AUS155-0032",
      "category": "140100-Computer Equipment",
      "description": "Samsung 55\" Crystal UHD Signage QMC (3 Warranty) - Ultra Slim Depth - Even Bezel - Centered VESA Holes",
      "location": "Singapore-AUS155",
      "department": "Technology Operations",
      "custodian": "",
      "acquisitionDate": "2025-06-26",
      "supplier": "",
      "invoice": "I-000081",
      "purchaseCost": "1755",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Internal ID 5763343. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0054",
      "tag": "AUS155-0033",
      "category": "140100-Computer Equipment",
      "description": "14inch MacBook Pro - Space Black",
      "location": "Singapore-AUS155",
      "department": "Technology Operations",
      "custodian": "",
      "acquisitionDate": "2025-06-18",
      "supplier": "KG Sowers Group Pte Ltd",
      "invoice": "INV/2025/00330",
      "purchaseCost": "2686.22",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Internal ID 5763344. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0055",
      "tag": "AUS155-0034",
      "category": "140100-Computer Equipment",
      "description": "Notebook ThinkPad P14s Gen 5 Windows 11 Pro 64 vPro Enterprise",
      "location": "Singapore-AUS155",
      "department": "Technology Operations",
      "custodian": "",
      "acquisitionDate": "2025-07-15",
      "supplier": "KG Sowers (Malaysia) Sdn Bhd",
      "invoice": "",
      "purchaseCost": "58200",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Internal ID 5867172. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0056",
      "tag": "AUS155-0035",
      "category": "140100-Computer Equipment",
      "description": "ThinkPad P14s Gen 5 and warranty",
      "location": "Singapore-AUS155",
      "department": "Technology Operations",
      "custodian": "",
      "acquisitionDate": "2025-07-28",
      "supplier": "KG Sowers Group Pte Ltd",
      "invoice": "",
      "purchaseCost": "2510.02",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Internal ID 5867173. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0057",
      "tag": "AUS155-0036",
      "category": "140100-Computer Equipment",
      "description": "13-inch iPad Pro Wi-Fi + Cellular 512GB with standard glass - Space Black",
      "location": "Singapore-AUS155",
      "department": "Technology Operations",
      "custodian": "",
      "acquisitionDate": "2025-07-16",
      "supplier": "KG Sowers Group Pte Ltd",
      "invoice": "",
      "purchaseCost": "5942.54",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Internal ID 5867174. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0058",
      "tag": "AUS155-0037",
      "category": "140100-Computer Equipment",
      "description": "ThinkPad P14s Gen 5 and other hardwares",
      "location": "Singapore-AUS155",
      "department": "Technology Operations",
      "custodian": "",
      "acquisitionDate": "2025-07-29",
      "supplier": "KG Sowers Group Pte Ltd",
      "invoice": "",
      "purchaseCost": "26139.56",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Internal ID 5867175. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0059",
      "tag": "AUS155-0043",
      "category": "140100-Computer Equipment",
      "description": "Lenovo ThinkVision S24i-30 23.8 inch Monitor",
      "location": "Malaysia-AUS155",
      "department": "Technology Operations",
      "custodian": "",
      "acquisitionDate": "2025-11-11",
      "supplier": "KG Sowers (Malaysia) Sdn Bhd",
      "invoice": "",
      "purchaseCost": "49510",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Internal ID 6542045. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0060",
      "tag": "AUS155-0044",
      "category": "140100-Computer Equipment",
      "description": "Notebook ThinkPad X1 2-in-1 Gen 10 21Q1C Windows 11 Pro 64 vPro Enterprise",
      "location": "Singapore-AUS155",
      "department": "Technology Operations",
      "custodian": "",
      "acquisitionDate": "2025-12-22",
      "supplier": "KG Sowers Group Pte Ltd",
      "invoice": "",
      "purchaseCost": "3119.4",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Internal ID 6842098. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0061",
      "tag": "AUS155-0045",
      "category": "140100-Computer Equipment",
      "description": "Notebook ThinkPad P14s Gen 6 Lenovo AI Now Windows 11 Pro 64 vPro Enterprise",
      "location": "Malaysia-AUS155",
      "department": "Technology Operations",
      "custodian": "",
      "acquisitionDate": "2026-03-24",
      "supplier": "KG Sowers (Malaysia) Sdn Bhd",
      "invoice": "KGM/2026/0003",
      "purchaseCost": "21990",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Internal ID 6842099. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0062",
      "tag": "AUS155-0046",
      "category": "140100-Computer Equipment",
      "description": "14-inch MacBook Pro + AppleCare",
      "location": "Singapore-AUS155",
      "department": "Technology Operations",
      "custodian": "",
      "acquisitionDate": "2026-04-07",
      "supplier": "KG Sowers Group Pte Ltd",
      "invoice": "INV/2026/00260",
      "purchaseCost": "2889.31",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Internal ID 6842101. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0063",
      "tag": "AUS155-0047",
      "category": "140100-Computer Equipment",
      "description": "2x Lenovo Notebook ThinkPad X1",
      "location": "Singapore-AUS155",
      "department": "Technology Operations",
      "custodian": "",
      "acquisitionDate": "2026-05-11",
      "supplier": "KG Sowers Group Pte Ltd",
      "invoice": "INV/2026/00347",
      "purchaseCost": "7528.44",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 3,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "3",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Internal ID 6842102. Source method: Prime Cost, life 3y"
    },
    {
      "id": "AUS155-0064",
      "tag": "APY00175",
      "category": "140200-Furniture and Equipment",
      "description": "Supply and install 2 x workstations Oct18",
      "location": "SINGAPORE",
      "department": "Corporate",
      "custodian": "",
      "acquisitionDate": "2018-10-26",
      "supplier": "CGET002",
      "invoice": "GETi-180280",
      "purchaseCost": "5338.54",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 5,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "5",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 7244 SGD. Internal ID 876240. Source method: Prime Cost, life 5y"
    },
    {
      "id": "AUS155-0065",
      "tag": "APY00176",
      "category": "140200-Furniture and Equipment",
      "description": "Supply&install server workstn,power/telph point",
      "location": "SINGAPORE",
      "department": "Corporate",
      "custodian": "",
      "acquisitionDate": "2018-06-05",
      "supplier": "CGET002",
      "invoice": "GETi-180232",
      "purchaseCost": "2063.49",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 5,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "5",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 2800 SGD. Internal ID 876241. Source method: Prime Cost, life 5y"
    },
    {
      "id": "AUS155-0066",
      "tag": "APY00177",
      "category": "140200-Furniture and Equipment",
      "description": "Office furnitures (2x chairs & 8x paintings)",
      "location": "SINGAPORE",
      "department": "Retail",
      "custodian": "",
      "acquisitionDate": "2017-10-17",
      "supplier": "CGET002",
      "invoice": "GETi170150",
      "purchaseCost": "734.01",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 5,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "5",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 996 SGD. Internal ID 876242. Source method: Prime Cost, life 5y"
    },
    {
      "id": "AUS155-0067",
      "tag": "APY00178",
      "category": "140200-Furniture and Equipment",
      "description": "M Koh - Furniture for Reception area 04/12/18",
      "location": "",
      "department": "Retail - Operations",
      "custodian": "",
      "acquisitionDate": "2018-12-04",
      "supplier": "ESG0005",
      "invoice": "EXP50809",
      "purchaseCost": "351.53",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 5,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "5",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 477 SGD. Internal ID 876243. Source method: Prime Cost, life 5y"
    },
    {
      "id": "AUS155-0068",
      "tag": "APY00189",
      "category": "140200-Furniture and Equipment",
      "description": "Tables & chairs for SG new office + dismantling",
      "location": "SINGAPORE",
      "department": "Corporate",
      "custodian": "",
      "acquisitionDate": "2019-08-16",
      "supplier": "CART002",
      "invoice": "IV-1908041",
      "purchaseCost": "4962.69",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 5,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "5",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 6734 SGD. Internal ID 876244. Source method: Prime Cost, life 5y"
    },
    {
      "id": "AUS155-0069",
      "tag": "APY00190",
      "category": "140200-Furniture and Equipment",
      "description": "Staff & Meeting chairs for SG new office",
      "location": "SINGAPORE",
      "department": "Corporate",
      "custodian": "",
      "acquisitionDate": "2019-08-19",
      "supplier": "CAME004",
      "invoice": "AOFINV-3278",
      "purchaseCost": "4606",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 5,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "5",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 6250 SGD. Internal ID 876245. Source method: Prime Cost, life 5y"
    },
    {
      "id": "AUS155-0070",
      "tag": "APY00192",
      "category": "140200-Furniture and Equipment",
      "description": "Tables & chairs for SG new office",
      "location": "PSYQUATION",
      "department": "Corporate",
      "custodian": "",
      "acquisitionDate": "2019-08-27",
      "supplier": "CART002",
      "invoice": "IV-1908060",
      "purchaseCost": "4432.69",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 5,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "5",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 6014.83 SGD. Internal ID 876246. Source method: Prime Cost, life 5y"
    },
    {
      "id": "AUS155-0071",
      "tag": "APY00193",
      "category": "140200-Furniture and Equipment",
      "description": "Tables and chairs - Affiliate Summit AsiaPac 2019",
      "location": "LONDON",
      "department": "Retail - Marketing",
      "custodian": "",
      "acquisitionDate": "2019-09-26",
      "supplier": "CPIC002",
      "invoice": "113_19011B",
      "purchaseCost": "818.03",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 5,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "5",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 1110 SGD. Internal ID 876247. Source method: Prime Cost, life 5y"
    },
    {
      "id": "AUS155-0072",
      "tag": "APY00194",
      "category": "140200-Furniture and Equipment",
      "description": "Furniture for reception area",
      "location": "SINGAPORE",
      "department": "Corporate",
      "custodian": "",
      "acquisitionDate": "2019-08-20",
      "supplier": "ESG0005",
      "invoice": "Mui Aug19 card *5192",
      "purchaseCost": "1001.23",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 5,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "5",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 1358.6 SGD. Internal ID 876248. Source method: Prime Cost, life 5y"
    },
    {
      "id": "AUS155-0073",
      "tag": "APY00197",
      "category": "140200-Furniture and Equipment",
      "description": "30x Training Chairs",
      "location": "SINGAPORE",
      "department": "Corporate",
      "custodian": "",
      "acquisitionDate": "2019-12-16",
      "supplier": "CAME004",
      "invoice": "AOFINV-3440",
      "purchaseCost": "2291.95",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 5,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "5",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 3110 SGD. Internal ID 876249. Source method: Prime Cost, life 5y"
    },
    {
      "id": "AUS155-0074",
      "tag": "APY00212",
      "category": "140220-Fixtures and Fittings",
      "description": "Aerohive AP130 Wireless Access Pt,Service estimate",
      "location": "SINGAPORE",
      "department": "IT - Support",
      "custodian": "",
      "acquisitionDate": "2019-08-26",
      "supplier": "CMIS001",
      "invoice": "1098314",
      "purchaseCost": "829.09",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 5,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "5",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 1185.6 AUD. Internal ID 876253. Source method: Prime Cost, life 5y"
    },
    {
      "id": "AUS155-0075",
      "tag": "APY00213",
      "category": "140220-Fixtures and Fittings",
      "description": "2x Canvas & frames for new SG office",
      "location": "SINGAPORE",
      "department": "Corporate",
      "custodian": "",
      "acquisitionDate": "2019-08-22",
      "supplier": "CTAL004",
      "invoice": "11458",
      "purchaseCost": "729.59",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 5,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "5",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 990 SGD. Internal ID 876254. Source method: Prime Cost, life 5y"
    },
    {
      "id": "AUS155-0076",
      "tag": "APY00214",
      "category": "140220-Fixtures and Fittings",
      "description": "3rd claims-30% deposit for Fitting-out Anson Rd",
      "location": "SINGAPORE",
      "department": "IT - Support",
      "custodian": "",
      "acquisitionDate": "2019-08-26",
      "supplier": "CGET002",
      "invoice": "GETi190387",
      "purchaseCost": "21301.39",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 5,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "5",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 28904.4 SGD. Internal ID 876255. Source method: Prime Cost, life 5y"
    },
    {
      "id": "AUS155-0077",
      "tag": "APY00224",
      "category": "140220-Fixtures and Fittings",
      "description": "Rework canvas in new SG office 09/09/19",
      "location": "SINGAPORE",
      "department": "Corporate",
      "custodian": "",
      "acquisitionDate": "2019-09-09",
      "supplier": "CTAL004",
      "invoice": "11562",
      "purchaseCost": "73.7",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 5,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "5",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 100 SGD. Internal ID 876256. Source method: Prime Cost, life 5y"
    },
    {
      "id": "AUS155-0078",
      "tag": "APY00234",
      "category": "140320-Leasehold Improvement",
      "description": "30% deposit for Fitting-out proj Anson Rd",
      "location": "SINGAPORE",
      "department": "IT - Support",
      "custodian": "",
      "acquisitionDate": "2019-07-29",
      "supplier": "CGET002",
      "invoice": "GETi-190375",
      "purchaseCost": "21301.39",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 5,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "5",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 28904.4 SGD. Internal ID 876257. Source method: Prime Cost, life 5y"
    },
    {
      "id": "AUS155-0079",
      "tag": "APY00239",
      "category": "140320-Leasehold Improvement",
      "description": "2nd claims-30% deposit for Fitting-out Anson Rd",
      "location": "SINGAPORE",
      "department": "IT - Support",
      "custodian": "",
      "acquisitionDate": "2019-08-07",
      "supplier": "CGET002",
      "invoice": "GETi190380",
      "purchaseCost": "21301.39",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 5,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "5",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 28904.4 SGD. Internal ID 876258. Source method: Prime Cost, life 5y"
    },
    {
      "id": "AUS155-0080",
      "tag": "APY00240",
      "category": "140320-Leasehold Improvement",
      "description": "4th claims of 10% final payment re GETQ190337",
      "location": "SINGAPORE",
      "department": "IT - Support",
      "custodian": "",
      "acquisitionDate": "2019-09-26",
      "supplier": "CGET002",
      "invoice": "GETi190396",
      "purchaseCost": "7100.46",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 5,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "5",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 9634.8 SGD. Internal ID 876259. Source method: Prime Cost, life 5y"
    },
    {
      "id": "AUS155-0081",
      "tag": "APY00243",
      "category": "140320-Leasehold Improvement",
      "description": "5th claims of payment re GETQ190337",
      "location": "SINGAPORE",
      "department": "IT - Support",
      "custodian": "",
      "acquisitionDate": "2019-10-17",
      "supplier": "CGET002",
      "invoice": "GETi190405",
      "purchaseCost": "4710.5",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 5,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "5",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 6391.8 SGD. Internal ID 876260. Source method: Prime Cost, life 5y"
    },
    {
      "id": "AUS155-0082",
      "tag": "APY00245",
      "category": "140320-Leasehold Improvement",
      "description": "Reinstatement works re quotation GETQ190336",
      "location": "SINGAPORE",
      "department": "IT - Support",
      "custodian": "",
      "acquisitionDate": "2019-09-26",
      "supplier": "CGET002",
      "invoice": "GETi190395",
      "purchaseCost": "13633.76",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 5,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "5",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Original cost 18500 SGD. Internal ID 876261. Source method: Prime Cost, life 5y"
    },
    {
      "id": "AUS155-0083",
      "tag": "A2200099",
      "category": "150100-Software Development",
      "description": "Lagom",
      "location": "155 - AXICORP PTE. LTD (SG) USD",
      "department": "Technology Operations",
      "custodian": "",
      "acquisitionDate": "2023-06-30",
      "supplier": "",
      "invoice": "",
      "purchaseCost": "4775.05",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 5,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "5",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Internal ID 2532241. Source method: Prime Cost, life 5y"
    },
    {
      "id": "AUS155-0084",
      "tag": "A2200103",
      "category": "150100-Software Development",
      "description": "Payments v2",
      "location": "155 - AXICORP PTE. LTD (SG) USD",
      "department": "Product",
      "custodian": "",
      "wipCategory": "150120-Asset WIP",
      "inServiceDate": "2024-07-01",
      "acquisitionDate": "2023-06-30",
      "supplier": "",
      "invoice": "",
      "purchaseCost": "12833.89",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 5,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "5",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Acquired 2023-06-30. Internal ID 2532246. Source method: Prime Cost, life 5y"
    },
    {
      "id": "AUS155-0085",
      "tag": "A2200106",
      "category": "150100-Software Development",
      "description": "Axi Select",
      "location": "155 - AXICORP PTE. LTD (SG) USD",
      "department": "Product",
      "custodian": "",
      "wipCategory": "150120-Asset WIP",
      "inServiceDate": "2023-09-01",
      "acquisitionDate": "2023-06-30",
      "supplier": "",
      "invoice": "",
      "purchaseCost": "4775.06",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 5,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "5",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Acquired 2023-06-30. Internal ID 2532248. Source method: Prime Cost, life 5y"
    },
    {
      "id": "AUS155-0086",
      "tag": "A2200110",
      "category": "150100-Software Development",
      "description": "Client Data - Onboarding",
      "location": "155 - AXICORP PTE. LTD (SG) USD",
      "department": "Product",
      "custodian": "",
      "wipCategory": "150120-Asset WIP",
      "inServiceDate": "2024-07-01",
      "acquisitionDate": "2023-06-30",
      "supplier": "",
      "invoice": "",
      "purchaseCost": "46323.15",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 5,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "5",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Acquired 2023-06-30. Internal ID 2532251. Source method: Prime Cost, life 5y"
    },
    {
      "id": "AUS155-0087",
      "tag": "AUS155-0007",
      "category": "150100-Software Development",
      "description": "Tech Capitalisation FY24 - ATP",
      "location": "",
      "department": "Technology Operations",
      "custodian": "",
      "wipCategory": "150120-Asset WIP",
      "inServiceDate": "2024-07-01",
      "acquisitionDate": "2024-06-30",
      "supplier": "",
      "invoice": "",
      "purchaseCost": "165175.08",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 5,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "5",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Acquired 2024-06-30. Internal ID 4181885. Source method: Prime Cost, life 5y"
    },
    {
      "id": "AUS155-0088",
      "tag": "AUS155-0008",
      "category": "150100-Software Development",
      "description": "Tech Capitalisation FY24 - Automated Leverage Change",
      "location": "",
      "department": "Technology Operations",
      "custodian": "",
      "wipCategory": "150120-Asset WIP",
      "inServiceDate": "2024-07-01",
      "acquisitionDate": "2024-06-30",
      "supplier": "",
      "invoice": "",
      "purchaseCost": "47076.41",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 5,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "5",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Acquired 2024-06-30. Internal ID 4181886. Source method: Prime Cost, life 5y"
    },
    {
      "id": "AUS155-0089",
      "tag": "AUS155-0009",
      "category": "150100-Software Development",
      "description": "Tech Capitalisation FY24 - Axi Select",
      "location": "",
      "department": "Technology Operations",
      "custodian": "",
      "wipCategory": "150120-Asset WIP",
      "inServiceDate": "2024-07-01",
      "acquisitionDate": "2024-06-30",
      "supplier": "",
      "invoice": "",
      "purchaseCost": "47076.42",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 5,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "5",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Acquired 2024-06-30. Internal ID 4181887. Source method: Prime Cost, life 5y"
    },
    {
      "id": "AUS155-0090",
      "tag": "AUS155-0010",
      "category": "150100-Software Development",
      "description": "Tech Capitalisation FY24 - Back Office",
      "location": "",
      "department": "Technology Operations",
      "custodian": "",
      "wipCategory": "150120-Asset WIP",
      "inServiceDate": "2024-07-01",
      "acquisitionDate": "2024-06-30",
      "supplier": "",
      "invoice": "",
      "purchaseCost": "135754.63",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 5,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "5",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Acquired 2024-06-30. Internal ID 4181888. Source method: Prime Cost, life 5y"
    },
    {
      "id": "AUS155-0091",
      "tag": "AUS155-0011",
      "category": "150100-Software Development",
      "description": "Tech Capitalisation FY24 - Client Data On-Boarding",
      "location": "",
      "department": "Product",
      "custodian": "",
      "wipCategory": "150120-Asset WIP",
      "inServiceDate": "2024-07-01",
      "acquisitionDate": "2024-06-30",
      "supplier": "",
      "invoice": "",
      "purchaseCost": "47076.42",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 5,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "5",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Acquired 2024-06-30. Internal ID 4181889. Source method: Prime Cost, life 5y"
    },
    {
      "id": "AUS155-0092",
      "tag": "AUS155-0012",
      "category": "150100-Software Development",
      "description": "Tech Capitalisation FY24 - Data Platform",
      "location": "",
      "department": "Product",
      "custodian": "",
      "wipCategory": "150120-Asset WIP",
      "inServiceDate": "2024-07-01",
      "acquisitionDate": "2024-06-30",
      "supplier": "",
      "invoice": "",
      "purchaseCost": "47076.42",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 5,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "5",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Acquired 2024-06-30. Internal ID 4181890. Source method: Prime Cost, life 5y"
    },
    {
      "id": "AUS155-0093",
      "tag": "AUS155-0013",
      "category": "150100-Software Development",
      "description": "Tech Capitalisation FY24 - OB Lite",
      "location": "",
      "department": "Technology Operations",
      "custodian": "",
      "wipCategory": "150120-Asset WIP",
      "inServiceDate": "2024-07-01",
      "acquisitionDate": "2024-06-30",
      "supplier": "",
      "invoice": "",
      "purchaseCost": "47076.42",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 5,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "5",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Acquired 2024-06-30. Internal ID 4181891. Source method: Prime Cost, life 5y"
    },
    {
      "id": "AUS155-0094",
      "tag": "AUS155-0014",
      "category": "150100-Software Development",
      "description": "Tech Capitalisation FY24 - Payment V2",
      "location": "",
      "department": "Product",
      "custodian": "",
      "wipCategory": "150120-Asset WIP",
      "inServiceDate": "2024-07-01",
      "acquisitionDate": "2024-06-30",
      "supplier": "",
      "invoice": "",
      "purchaseCost": "321743.31",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 5,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "5",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Acquired 2024-06-30. Internal ID 4181892. Source method: Prime Cost, life 5y"
    },
    {
      "id": "AUS155-0095",
      "tag": "AUS155-0024",
      "category": "150100-Software Development",
      "description": "Axi Select FY25",
      "location": "Singapore-AUS155",
      "department": "IT - Development, Technology Operations",
      "custodian": "",
      "wipCategory": "150120-Asset WIP",
      "inServiceDate": "2025-07-01",
      "acquisitionDate": "2024-11-30",
      "supplier": "",
      "invoice": "",
      "purchaseCost": "267369.95",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 5,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "5",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Acquired 2024-11-30. Internal ID 4798059. Source method: Prime Cost, life 5y"
    },
    {
      "id": "AUS155-0096",
      "tag": "AUS155-0025",
      "category": "150100-Software Development",
      "description": "Back Office FY25",
      "location": "Singapore-AUS155",
      "department": "IT - Development, Technology Operations",
      "custodian": "",
      "wipCategory": "150120-Asset WIP",
      "inServiceDate": "2025-07-01",
      "acquisitionDate": "2024-11-30",
      "supplier": "",
      "invoice": "",
      "purchaseCost": "510767.62",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 5,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "5",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Acquired 2024-11-30. Internal ID 5867183. Source method: Prime Cost, life 5y"
    },
    {
      "id": "AUS155-0097",
      "tag": "AUS155-0027",
      "category": "150100-Software Development",
      "description": "Client - Data Onboarding FY25",
      "location": "Singapore-AUS155",
      "department": "IT - Development, Technology Operations",
      "custodian": "",
      "wipCategory": "150120-Asset WIP",
      "inServiceDate": "2025-07-01",
      "acquisitionDate": "2024-11-30",
      "supplier": "",
      "invoice": "",
      "purchaseCost": "269658.36",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 5,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "5",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Acquired 2024-11-30. Internal ID 4798062. Source method: Prime Cost, life 5y"
    },
    {
      "id": "AUS155-0098",
      "tag": "AUS155-0028",
      "category": "150100-Software Development",
      "description": "Lagom FY25",
      "location": "Singapore-AUS155",
      "department": "IT - Development, Technology Operations",
      "custodian": "",
      "wipCategory": "150120-Asset WIP",
      "inServiceDate": "2025-07-01",
      "acquisitionDate": "2024-11-30",
      "supplier": "",
      "invoice": "",
      "purchaseCost": "308561.38",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 5,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "5",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Acquired 2024-11-30. Internal ID 4798063. Source method: Prime Cost, life 5y"
    },
    {
      "id": "AUS155-0099",
      "tag": "AUS155-0029",
      "category": "150100-Software Development",
      "description": "Pay V2 FY25 SGD",
      "location": "Singapore-AUS155",
      "department": "IT - Development, Technology Operations",
      "custodian": "",
      "wipCategory": "150120-Asset WIP",
      "inServiceDate": "2025-07-01",
      "acquisitionDate": "2024-11-30",
      "supplier": "",
      "invoice": "",
      "purchaseCost": "13434.13",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 5,
      "residualValue": "0",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "5",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Acquired 2024-11-30. Internal ID 4798064. Source method: Prime Cost, life 5y"
    },
    {
      "id": "AUS155-0100",
      "tag": "AUS155-0038",
      "category": "150120-Asset WIP",
      "description": "Back Office FY26",
      "location": "Singapore-AUS155",
      "department": "Product",
      "custodian": "",
      "acquisitionDate": "2026-06-30",
      "supplier": "",
      "invoice": "",
      "purchaseCost": "21795",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 5,
      "residualValue": "21795",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Work in progress (not yet in service). Acquired 2025-07-01. Internal ID 6133152. Source method: Prime Cost, life 5y"
    },
    {
      "id": "AUS155-0101",
      "tag": "AUS155-0039",
      "category": "150120-Asset WIP",
      "description": "Pay V2 FY26",
      "location": "Singapore-AUS155",
      "department": "Product",
      "custodian": "",
      "acquisitionDate": "2026-06-30",
      "supplier": "",
      "invoice": "",
      "purchaseCost": "2770",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 5,
      "residualValue": "2770",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Work in progress (not yet in service). Acquired 2025-07-01. Internal ID 6133153. Source method: Prime Cost, life 5y"
    },
    {
      "id": "AUS155-0102",
      "tag": "AUS155-0040",
      "category": "150120-Asset WIP",
      "description": "Lagom FY26",
      "location": "Singapore-AUS155",
      "department": "Product",
      "custodian": "",
      "acquisitionDate": "2026-06-30",
      "supplier": "",
      "invoice": "",
      "purchaseCost": "15681",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 5,
      "residualValue": "15681",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Work in progress (not yet in service). Acquired 2025-07-01. Internal ID 6133154. Source method: Prime Cost, life 5y"
    },
    {
      "id": "AUS155-0103",
      "tag": "AUS155-0041",
      "category": "150120-Asset WIP",
      "description": "Axi Select FY26",
      "location": "Singapore-AUS155",
      "department": "Product",
      "custodian": "",
      "acquisitionDate": "2026-06-30",
      "supplier": "",
      "invoice": "",
      "purchaseCost": "12438",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 5,
      "residualValue": "12438",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Work in progress (not yet in service). Acquired 2025-07-01. Internal ID 6133155. Source method: Prime Cost, life 5y"
    },
    {
      "id": "AUS155-0104",
      "tag": "AUS155-0042",
      "category": "150120-Asset WIP",
      "description": "Client Onboarding FY26",
      "location": "Singapore-AUS155",
      "department": "Product",
      "custodian": "",
      "acquisitionDate": "2026-06-30",
      "supplier": "",
      "invoice": "",
      "purchaseCost": "12618",
      "installationCost": "",
      "otherCost": "",
      "acctMethod": "straight-line",
      "usefulLife": 5,
      "residualValue": "12618",
      "acctRate": "",
      "taxCostOverride": "",
      "taxMethod": "prime-cost",
      "taxRate": "",
      "taxLife": "",
      "taxInitialAllowance": "",
      "disposed": false,
      "disposalDate": "",
      "disposalProceeds": "",
      "notes": "Work in progress (not yet in service). Acquired 2025-07-01. Internal ID 6133156. Source method: Prime Cost, life 5y"
    }
  ]
};
