window.AUS501 = {
    "version":  "AUS501-2025-06-30.5",
    "settings":  {
                     "companyName":  "CB Financial Services Limited (UK) - AUS501",
                     "currency":  "$",
                     "fyEndMonth":  6,
                     "fyEndDay":  30,
                     "reportingDate":  "2025-06-30",
                     "dtRate":  25
                 },
    "assets":  [
                   {
                       "id":  "AUS501-CE-A2200003",
                       "tag":  "A2200003",
                       "category":  "140100-Computer Equipment",
                       "description":  "Apple MacBook Pro Laptop 16 SL",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "",
                       "inServiceDate":  "2021-07-23",
                       "acquisitionDate":  "2021-07-23",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "2480.99",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  3,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "3",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-CE-A2200004",
                       "tag":  "A2200004",
                       "category":  "140100-Computer Equipment",
                       "description":  "Apple MacBook Pro Laptop 16.0 SL",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "",
                       "inServiceDate":  "2021-07-23",
                       "acquisitionDate":  "2021-07-23",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "2480.99",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  3,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "3",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-CE-A2200006",
                       "tag":  "A2200006",
                       "category":  "140100-Computer Equipment",
                       "description":  "Lenovo ThinkStation P340 Workstation PC",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "",
                       "inServiceDate":  "2021-07-07",
                       "acquisitionDate":  "2021-07-07",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "3691.14",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  3,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "3",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-CE-A2200009",
                       "tag":  "A2200009",
                       "category":  "140100-Computer Equipment",
                       "description":  "Apple MacBook Pro Laptop 16.0",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "",
                       "inServiceDate":  "2021-08-13",
                       "acquisitionDate":  "2021-08-13",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "2501.08",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  3,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "3",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-CE-A2200011",
                       "tag":  "A2200011",
                       "category":  "140100-Computer Equipment",
                       "description":  "Apple MacBook Pro 16-inch i7",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "",
                       "inServiceDate":  "2021-09-07",
                       "acquisitionDate":  "2021-09-07",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "2507.79",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  3,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "3",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-CE-A2200092",
                       "tag":  "A2200092",
                       "category":  "140100-Computer Equipment",
                       "description":  "Lenovo Keyboard/Mouse (30) \u0026 ThinkVision (10)",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "",
                       "inServiceDate":  "2022-06-27",
                       "acquisitionDate":  "2022-06-27",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "3601.73",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  3,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "3",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-CE-A2300001",
                       "tag":  "A2300001",
                       "category":  "140100-Computer Equipment",
                       "description":  "Lenovo ThinkVision T24i-2L",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "",
                       "inServiceDate":  "2022-07-01",
                       "acquisitionDate":  "2022-07-01",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "2165.18",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  3,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "3",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-CE-A2300002",
                       "tag":  "A2300002",
                       "category":  "140100-Computer Equipment",
                       "description":  "TP Thunderbolt 3 WS Dock Gen 2",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "",
                       "inServiceDate":  "2022-07-01",
                       "acquisitionDate":  "2022-07-01",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "3227.44",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  3,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "3",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-CE-A2300005",
                       "tag":  "A2300005",
                       "category":  "140100-Computer Equipment",
                       "description":  "7 Jabra Evolve2 40 Headset",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "",
                       "inServiceDate":  "2022-07-25",
                       "acquisitionDate":  "2022-07-25",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "638.18",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  3,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "3",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-CE-A2300006",
                       "tag":  "A2300006",
                       "category":  "140100-Computer Equipment",
                       "description":  "6 NB X1 G6 i7 14.0 16G 512GB",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "",
                       "inServiceDate":  "2022-07-25",
                       "acquisitionDate":  "2022-07-25",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "13493.90",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  3,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "3",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-CE-A2300007",
                       "tag":  "A2300007",
                       "category":  "140100-Computer Equipment",
                       "description":  "6 Lenovo Premier Support Onsite NBD",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "",
                       "inServiceDate":  "2022-07-25",
                       "acquisitionDate":  "2022-07-25",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "363.61",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  3,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "3",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-CE-A2300012",
                       "tag":  "A2300012",
                       "category":  "140100-Computer Equipment",
                       "description":  "Neat Bar Pro Bundle",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "",
                       "inServiceDate":  "2022-08-25",
                       "acquisitionDate":  "2022-08-25",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "5331.59",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  3,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "3",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-CE-A2300019",
                       "tag":  "A2300019",
                       "category":  "140100-Computer Equipment",
                       "description":  "Lenovo ThinkPad X1 Yoga Hybrid 14 2in1",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "",
                       "inServiceDate":  "2022-07-20",
                       "acquisitionDate":  "2022-07-20",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "3070.28",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  3,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "3",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-CE-A2300020",
                       "tag":  "A2300020",
                       "category":  "140100-Computer Equipment",
                       "description":  "Lenovo ThinkPad X1 Yoga Hybrid 14 2in1",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "",
                       "inServiceDate":  "2022-07-20",
                       "acquisitionDate":  "2022-07-20",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "3070.28",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  3,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "3",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-CE-A2300021",
                       "tag":  "A2300021",
                       "category":  "140100-Computer Equipment",
                       "description":  "Lenovo ThinkPad X1 Yoga Hybrid 14 2in1",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "",
                       "inServiceDate":  "2022-07-20",
                       "acquisitionDate":  "2022-07-20",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "3070.28",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  3,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "3",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-CE-A2300022",
                       "tag":  "A2300022",
                       "category":  "140100-Computer Equipment",
                       "description":  "Apple MacBook Pro 16.2 M1 Pro",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "",
                       "inServiceDate":  "2022-09-30",
                       "acquisitionDate":  "2022-09-30",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "2138.81",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  3,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "3",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-CE-A2300023",
                       "tag":  "A2300023",
                       "category":  "140100-Computer Equipment",
                       "description":  "ThinkPad Hybrid USB-C with USB-A Dock (10)",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "",
                       "inServiceDate":  "2022-10-04",
                       "acquisitionDate":  "2022-10-04",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "2285.82",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  3,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "3",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-CE-A2300024",
                       "tag":  "A2300024",
                       "category":  "140100-Computer Equipment",
                       "description":  "Apple MacBook Pro 16.2 M1 Pro (1)",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "",
                       "inServiceDate":  "2022-09-14",
                       "acquisitionDate":  "2022-09-14",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "2199.62",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  3,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "3",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-CE-A2300025",
                       "tag":  "A2300025",
                       "category":  "140100-Computer Equipment",
                       "description":  "Apple MacBook Pro 16.2 M1 Pro (2) \u0026 X1 G6 (6)",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "",
                       "inServiceDate":  "2022-09-14",
                       "acquisitionDate":  "2022-09-14",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "22112.74",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  3,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "3",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-CE-A2300027",
                       "tag":  "A2300027",
                       "category":  "140100-Computer Equipment",
                       "description":  "20XYCTO1WW ThinkPad remaining balance",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "",
                       "inServiceDate":  "2022-05-18",
                       "acquisitionDate":  "2022-05-18",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "899.78",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  3,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "3",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-CE-A2300037",
                       "tag":  "A2300037",
                       "category":  "140100-Computer Equipment",
                       "description":  "Lenovo ThinkPad X1 Yoga G7 i (6)",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "",
                       "inServiceDate":  "2022-12-20",
                       "acquisitionDate":  "2022-12-20",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "13077.75",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  3,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "3",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-CE-APY00053",
                       "tag":  "APY00053",
                       "category":  "140100-Computer Equipment",
                       "description":  "Blank data tape",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "",
                       "inServiceDate":  "2019-09-01",
                       "acquisitionDate":  "2019-09-01",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "186.01",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  3,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "3",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-CE-APY00054",
                       "tag":  "APY00054",
                       "category":  "140100-Computer Equipment",
                       "description":  "Blank data tape",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "",
                       "inServiceDate":  "2019-09-01",
                       "acquisitionDate":  "2019-09-01",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "567.40",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  3,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "3",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-CE-APY00107",
                       "tag":  "APY00107",
                       "category":  "140100-Computer Equipment",
                       "description":  "28x Lenovo Thinkpad 14 slim Topload",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "",
                       "inServiceDate":  "2020-07-20",
                       "acquisitionDate":  "2020-07-20",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "1261.47",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  3,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "3",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-CE-APY00108",
                       "tag":  "APY00108",
                       "category":  "140100-Computer Equipment",
                       "description":  "28x X1 Yoga 4th Gen i7 16GB 512GB",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "",
                       "inServiceDate":  "2020-07-20",
                       "acquisitionDate":  "2020-07-20",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "62942.40",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  3,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "3",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-CE-APY00109",
                       "tag":  "APY00109",
                       "category":  "140100-Computer Equipment",
                       "description":  "28x Lenovo 3Y Premier Support",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "",
                       "inServiceDate":  "2020-07-23",
                       "acquisitionDate":  "2020-07-23",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "2002.65",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  3,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "3",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-CE-APY00118",
                       "tag":  "APY00118",
                       "category":  "140100-Computer Equipment",
                       "description":  "28x Lenovo Thinkpad Hybrid USB-C dock",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "",
                       "inServiceDate":  "2020-07-30",
                       "acquisitionDate":  "2020-07-30",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "6054.10",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  3,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "3",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-CE-APY00120",
                       "tag":  "APY00120",
                       "category":  "140100-Computer Equipment",
                       "description":  "2x UltraSharp UP2716D QHD",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "",
                       "inServiceDate":  "2020-07-15",
                       "acquisitionDate":  "2020-07-15",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "1316.01",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  3,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "3",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-CE-APY00121",
                       "tag":  "APY00121",
                       "category":  "140100-Computer Equipment",
                       "description":  "1x ThinkPad Hybrid USB-C with USB-A",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "",
                       "inServiceDate":  "2020-07-17",
                       "acquisitionDate":  "2020-07-17",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "209.31",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  3,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "3",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-CE-AUS501-0009",
                       "tag":  "AUS501-0009",
                       "category":  "140100-Computer Equipment",
                       "description":  "Lenovo ThinkPad P14s Gen 4",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "",
                       "inServiceDate":  "2024-06-20",
                       "acquisitionDate":  "2024-06-20",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "12429.27",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  3,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "3",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-CE-AUS501-0010",
                       "tag":  "AUS501-0010",
                       "category":  "140100-Computer Equipment",
                       "description":  "MacBook Pro 16 M3 Max 64GB 1TB",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "",
                       "inServiceDate":  "2024-09-06",
                       "acquisitionDate":  "2024-09-06",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "4919.83",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  3,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "3",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-CE-AUS501-0011",
                       "tag":  "AUS501-0011",
                       "category":  "140100-Computer Equipment",
                       "description":  "Lenovo Notebook ThinkPad P14s Gen 5",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "",
                       "inServiceDate":  "2024-10-21",
                       "acquisitionDate":  "2024-10-21",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "2339.10",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  3,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "3",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-CE-AUS501-0018",
                       "tag":  "AUS501-0018",
                       "category":  "140100-Computer Equipment",
                       "description":  "Apple MacBook Pro 16.2 M4 Pro 48GB",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "",
                       "inServiceDate":  "2025-04-07",
                       "acquisitionDate":  "2025-04-07",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "2965.98",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  3,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "3",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-FE-A2200052",
                       "tag":  "A2200052",
                       "category":  "140200-Furniture and Equipment",
                       "description":  "One Financial Markets",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "",
                       "inServiceDate":  "2021-10-07",
                       "acquisitionDate":  "2021-10-07",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "1338.30",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  5,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "5",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-FE-A2200080",
                       "tag":  "A2200080",
                       "category":  "140200-Furniture and Equipment",
                       "description":  "Neat Bar Pro \u0026 Pad (2)",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "",
                       "inServiceDate":  "2022-05-24",
                       "acquisitionDate":  "2022-05-24",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "9144.53",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  5,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "5",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-FE-A2300008",
                       "tag":  "A2300008",
                       "category":  "140200-Furniture and Equipment",
                       "description":  "Office furniture per FF\u0026E schedule",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "",
                       "inServiceDate":  "2022-06-23",
                       "acquisitionDate":  "2022-06-23",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "31174.13",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  5,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "5",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-SD-Lagom",
                       "tag":  "A2200100",
                       "category":  "150100-Software Development",
                       "description":  "Lagom",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "",
                       "inServiceDate":  "2023-06-30",
                       "acquisitionDate":  "2023-06-30",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "840022.99",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  5,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "5",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-SD-BackOff",
                       "tag":  "A2200101",
                       "category":  "150100-Software Development",
                       "description":  "Back Office",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "",
                       "inServiceDate":  "2023-06-30",
                       "acquisitionDate":  "2023-06-30",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "796631.79",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  5,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "5",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-SD-AxiSel",
                       "tag":  "A2200107",
                       "category":  "150100-Software Development",
                       "description":  "Axi Select",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "",
                       "inServiceDate":  "2023-09-01",
                       "acquisitionDate":  "2023-09-01",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "88131.25",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  5,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "5",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-WT-A2200104",
                       "tag":  "A2200104",
                       "category":  "150100-Software Development",
                       "description":  "WIP transfer - Payments v2",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "150120-Asset WIP",
                       "inServiceDate":  "2024-07-01",
                       "acquisitionDate":  "2023-06-30",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "362653.62",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  5,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "5",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-WT-A2200111",
                       "tag":  "A2200111",
                       "category":  "150100-Software Development",
                       "description":  "WIP transfer - Client Data - Onboarding",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "150120-Asset WIP",
                       "inServiceDate":  "2024-07-01",
                       "acquisitionDate":  "2023-06-30",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "407753.55",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  5,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "5",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-WT-AUS501-0001",
                       "tag":  "AUS501-0001",
                       "category":  "150100-Software Development",
                       "description":  "WIP transfer - ATP",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "150120-Asset WIP",
                       "inServiceDate":  "2024-07-01",
                       "acquisitionDate":  "2024-06-30",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "700055.62",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  5,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "5",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-WT-AUS501-0002",
                       "tag":  "AUS501-0002",
                       "category":  "150100-Software Development",
                       "description":  "WIP transfer - Automated Leverage Change",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "150120-Asset WIP",
                       "inServiceDate":  "2024-07-01",
                       "acquisitionDate":  "2024-06-30",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "99387.36",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  5,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "5",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-WT-AUS501-0003",
                       "tag":  "AUS501-0003",
                       "category":  "150100-Software Development",
                       "description":  "WIP transfer - Axi Select",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "150120-Asset WIP",
                       "inServiceDate":  "2024-07-01",
                       "acquisitionDate":  "2024-06-30",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "305657.01",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  5,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "5",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-WT-AUS501-0004",
                       "tag":  "AUS501-0004",
                       "category":  "150100-Software Development",
                       "description":  "WIP transfer - Back Office",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "150120-Asset WIP",
                       "inServiceDate":  "2024-07-01",
                       "acquisitionDate":  "2024-06-30",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "272483.78",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  5,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "5",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-WT-AUS501-0005",
                       "tag":  "AUS501-0005",
                       "category":  "150100-Software Development",
                       "description":  "WIP transfer - Client Data On-Boarding",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "150120-Asset WIP",
                       "inServiceDate":  "2024-07-01",
                       "acquisitionDate":  "2024-06-30",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "114151.26",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  5,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "5",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-WT-AUS501-0006",
                       "tag":  "AUS501-0006",
                       "category":  "150100-Software Development",
                       "description":  "WIP transfer - Data Platform",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "150120-Asset WIP",
                       "inServiceDate":  "2024-07-01",
                       "acquisitionDate":  "2024-06-30",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "227693.27",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  5,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "5",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-WT-AUS501-0007",
                       "tag":  "AUS501-0007",
                       "category":  "150100-Software Development",
                       "description":  "WIP transfer - OB Lite",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "150120-Asset WIP",
                       "inServiceDate":  "2024-07-01",
                       "acquisitionDate":  "2024-06-30",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "99387.36",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  5,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "5",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-WT-AUS501-0008",
                       "tag":  "AUS501-0008",
                       "category":  "150100-Software Development",
                       "description":  "WIP transfer - Payment V2",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "150120-Asset WIP",
                       "inServiceDate":  "2024-07-01",
                       "acquisitionDate":  "2024-06-30",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "952900.11",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  5,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "5",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-WIP-AUS501-0012",
                       "tag":  "AUS501-0012",
                       "category":  "150100-Software Development",
                       "description":  "Axi Select FY25 USD",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "150120-Asset WIP",
                       "inServiceDate":  "2025-07-01",
                       "acquisitionDate":  "2024-11-30",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "94644.25",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  5,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "5",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-WIP-AUS501-0013",
                       "tag":  "AUS501-0013",
                       "category":  "150100-Software Development",
                       "description":  "Axi Select FY25 GBP",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "150120-Asset WIP",
                       "inServiceDate":  "2025-07-01",
                       "acquisitionDate":  "2024-11-30",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "429511.33",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  5,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "5",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-WIP-AUS501-0014",
                       "tag":  "AUS501-0014",
                       "category":  "150100-Software Development",
                       "description":  "Client Data Onboarding FY25",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "150120-Asset WIP",
                       "inServiceDate":  "2025-07-01",
                       "acquisitionDate":  "2024-11-30",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "479705.75",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  5,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "5",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-WIP-AUS501-0015",
                       "tag":  "AUS501-0015",
                       "category":  "150100-Software Development",
                       "description":  "Lagom FY25",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "150120-Asset WIP",
                       "inServiceDate":  "2025-07-01",
                       "acquisitionDate":  "2024-11-30",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "706999.25",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  5,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "5",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-WIP-AUS501-0016",
                       "tag":  "AUS501-0016",
                       "category":  "150100-Software Development",
                       "description":  "Pay V2 FY25",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "150120-Asset WIP",
                       "inServiceDate":  "2025-07-01",
                       "acquisitionDate":  "2024-11-30",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "518318.31",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  5,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "5",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-WIP-AUS501-0019",
                       "tag":  "AUS501-0019",
                       "category":  "150100-Software Development",
                       "description":  "One Zero Upgrade FY25",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "150120-Asset WIP",
                       "inServiceDate":  "2025-07-01",
                       "acquisitionDate":  "2025-06-30",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "11658.16",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  5,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "5",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-WIP-AUS501-0020",
                       "tag":  "AUS501-0020",
                       "category":  "150100-Software Development",
                       "description":  "Back Office FY25",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "wipCategory":  "150120-Asset WIP",
                       "inServiceDate":  "2025-07-01",
                       "acquisitionDate":  "2025-06-30",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "750909.76",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  5,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "5",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25. Real asset from the register. Tax = placeholder pending UK pooled capital allowances."
                   }
               ],
    "leases":  [

               ]
};
