window.AUS501 = {
    "version":  "AUS501-2025-06-30.3",
    "settings":  {
                     "companyName":  "CB Financial Services Limited (UK) - AUS501",
                     "currency":  "$",
                     "fyEndMonth":  6,
                     "fyEndDay":  30,
                     "reportingDate":  "2025-06-30",
                     "dtRate":  25
                 },
    "assets":  [
                   {
                       "id":  "AUS501-BF-CE",
                       "tag":  "CE-OPENING",
                       "category":  "140100-Computer Equipment",
                       "description":  "Computer equipment - brought forward (1 Jul 2024)",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "acquisitionDate":  "2022-07-01",
                       "inServiceDate":  "2022-07-01",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "181727.99",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  1.333466,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "2024-07-01",
                       "openingCost":  "181727.99",
                       "openingAccDep":  "136768",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "1.333466",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25, rebuilt from the general ledger. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-BF-FE",
                       "tag":  "FE-OPENING",
                       "category":  "140200-Furniture and Equipment",
                       "description":  "Furniture \u0026 equipment - brought forward (1 Jul 2024)",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "acquisitionDate":  "2021-07-01",
                       "inServiceDate":  "2021-07-01",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "41656.96",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  2.93702,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "2024-07-01",
                       "openingCost":  "41656.96",
                       "openingAccDep":  "17184.71",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "2.93702",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25, rebuilt from the general ledger. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-BF-SD",
                       "tag":  "SD-OPENING",
                       "category":  "150100-Software Development",
                       "description":  "Software development - brought forward (1 Jul 2024)",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "acquisitionDate":  "2023-06-30",
                       "inServiceDate":  "2023-06-30",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "1636654.78",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  1.225094,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "2024-07-01",
                       "openingCost":  "1636654.78",
                       "openingAccDep":  "328227.76",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "1.225094",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25, rebuilt from the general ledger. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-ADD-CE",
                       "tag":  "CE-ADD-FY25",
                       "category":  "140100-Computer Equipment",
                       "description":  "Computer equipment - FY25 additions",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "acquisitionDate":  "2025-06-30",
                       "inServiceDate":  "2025-07-01",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "9874.52",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  3,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "3",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25, rebuilt from the general ledger. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-ADD-SD",
                       "tag":  "SD-ADD-FY25",
                       "category":  "150100-Software Development",
                       "description":  "Software development - FY25 capitalisations (WIP transferred in)",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "acquisitionDate":  "2025-06-30",
                       "inServiceDate":  "2025-07-01",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "3630254.2",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  5,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "5",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25, rebuilt from the general ledger. Tax = placeholder pending UK pooled capital allowances."
                   },
                   {
                       "id":  "AUS501-WIP-FY25",
                       "tag":  "WIP-FY25",
                       "category":  "150120-Asset WIP",
                       "description":  "Asset WIP - FY25 capitalisations (not yet in service)",
                       "location":  "United Kingdom-AUS501",
                       "department":  "",
                       "custodian":  "",
                       "acquisitionDate":  "2025-06-30",
                       "inServiceDate":  "2025-07-01",
                       "supplier":  "",
                       "invoice":  "",
                       "purchaseCost":  "2991746.8",
                       "installationCost":  "",
                       "otherCost":  "",
                       "acctMethod":  "straight-line",
                       "usefulLife":  5,
                       "residualValue":  "0",
                       "acctRate":  "",
                       "openingDate":  "",
                       "openingCost":  "",
                       "openingAccDep":  "",
                       "taxCostOverride":  "",
                       "taxMethod":  "straight-line",
                       "taxRate":  "",
                       "taxLife":  "5",
                       "taxInitialAllowance":  "0",
                       "disposed":  false,
                       "disposalDate":  "",
                       "disposalProceeds":  "",
                       "notes":  "UK AUS501 FY25, rebuilt from the general ledger. Tax = placeholder pending UK pooled capital allowances."
                   }
               ],
    "leases":  [

               ]
};
